"""Metadata for insecure_tree. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__credits__",
    "__description__",
    "__keywords__",
    "__license__",
    "__readme__",
    "__requires_python__",
    "__status__",
    "__title__",
    "__version__",
]

__title__ = "insecure_tree"
__version__ = "0.1.0"
__description__ = "Audit GitHub Actions security posture of your Python dependency tree using zizmor"
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["security", "supply-chain", "github-actions", "zizmor", "dependencies", "audit", "devsecops"]
__license__ = "MIT"
__requires_python__ = ">=3.10"
__status__ = "3 - Alpha"
